grammar org.xtext.example.SA.Simple_Assignment2 with org.eclipse.xtext.common.Terminals

generate domainmodel "http://www.xtext.org/example/domainmodel/Domainmodel"

DomainModel:
	model = AbstractElement
;

AbstractElement:
	Import | pd=PackageDeclaration
;

Import:
	'import' QualifiedNameWithWildcard
;

QualifiedNameWithWildcard:
	QualifiedName '.*'?
;

QualifiedName:
	ID('.' ID)*
;
 
 PackageDeclaration:
 	p='package'	
 ;